// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'App': string;
  'actions': string;
  'body': string;
  'icon': string;
  'size': string;
}
declare var cssExports: CssExports;
export = cssExports;
